[ldap]
# LDAP secrets file, example conetents:
# ldap_uris = "ldaps://mycompany.local:636"
# ldap_version = "3"
# ldap_auth_dn = "vmail@mycompany.local"
# ldap_auth_dn_password = "secret"
# ldap_base = "ou=company,dc=mycompany,dc=local"

ldap_config_file = "/etc/ldap/dovecot.conf"

# Check for this String in LDAP group's DN for this group to be treated as sharing group
ldap_groups_filter = "ou=departments"

[mailboxes]
maildir_location = "/mnt/mail/mailboxes"
inbox_name = "INBOX"
sent_name = "Sent"
drafts_name = "Drafts"
junk_name = "Spam"
trash_name = "Trash"
archive_name = "Archive"

[virtual]
virtual_all_name = "All"

[acl]
rights_admin = "lrwstipekxa"
rights_full = "lrwstipekx"
rights_write = "lrwstip"
rights_read = "lrws"
rights_see = "lr"

[debug]
debug_log = true
